### ISSUE TITLE
Git module

### ISSUE THREAD

**Issue by PPCM** [xenoz0718/goorm#130]
This IDE looks great and it works fine
Is there a roadmap for GIT module?

Thanks a lot for your response

**Comment by xenoz0718** [comment]
Thanks for your interest!

Now, we are preparing the next version of goorm and it will support git/subversion.
If you watch us continuously, you can meet this new feature a few month later...
At that time, this repository maybe closed and new repository will be opened on github.

Also, we are developing our goorm as a cloud service. 
Although this service infra locates on east asia region and you may feel this is slow, you can access via http://goorm.io.
The beta service of goorm 2.1 will launch soon (maybe at the end of January?)
