### ISSUE TITLE
맥에서 설치테스트 중인데요. 

### ISSUE THREAD

**Issue by Armdiri** [xenoz0718/goorm#131]
```
module.js : 340
    throw err ;
Error : Cannot find module 'socket.io/node_modules/redis'
```
여기에서 막히네요.
socket.io 1.3.5 는 설치 했는뎅 뭐가 문제인지.. 혹.. redis 문제?

**Comment by xenoz0718** [comment]
안녕하세요. socket.io를 local로 다시 설치해보시는 게 좋을 거 같습니다. 
그런데 현재 최신 버전의 socket.io는 지원하지 않고 있어서...

그리고 이 레파지토리도 최신 버전이 아니며, OSS 버전의 구름 2.1은 올 하반기에 다른 레파지토리에서 공개될 예정입니다.
